"""CNN sheet-reader regression tests.

Replays a curated set of normalized-input dumps (01_CNN_refactor/
regression_dumps/) through cnn_reader._read_sheet and compares the result
against a golden manifest.  This is CI-able without the gitignored
phone_sheets/ corpus:

  - card-detection (cards == manifest) catches geometry regressions — the
    historical failure mode (header detection, uneven layouts, bad lattice);
  - per-cell grid equality (decimal values, exact match) catches decode /
    cell-extraction regressions;
  - error cases must keep failing (we freeze the expected retake errors, so
    a change that silently starts/stopped erroring is flagged).

The manifest is generated by the currently-known-good reader.  Regenerate
it deliberately after an intentional improvement (never on a red CI!):

    .venv/bin/python test_scan_regression.py --rewrite-manifest

Run locally:

    .venv/bin/python -m pytest test_scan_regression.py -v
"""

import json
import sys
from pathlib import Path

import cv2
import pytest

REPO = Path(__file__).resolve().parent
CNN = REPO / "01_CNN_refactor"
sys.path.insert(0, str(CNN))

import cnn_reader  # noqa: E402

DUMP_DIR = CNN / "regression_dumps"
MANIFEST = DUMP_DIR / "manifest.json"
FREE = (2, 2)


def _grid_values(payload, card_index):
    return [[cell["value"] for cell in row]
            for row in payload["cards"][card_index]["grid"]]


@pytest.fixture(scope="session")
def model():
    return cnn_reader.load_model()


def _dump_cases():
    manifest = json.loads(MANIFEST.read_text())
    cases = []
    for ts, exp in sorted(manifest.items(), key=lambda kv: int(kv[0])):
        png = DUMP_DIR / f"in_{ts}.png"
        if not png.is_file():
            raise AssertionError(f"missing dump for manifest entry {ts}: {png}")
        cases.append((ts, png, exp))
    return cases


CASES = _dump_cases()


@pytest.mark.parametrize("ts,png,exp", CASES, ids=[c[0] for c in CASES])
def test_reader_matches_golden(model, ts, png, exp):
    sheet_bgr = cv2.imread(str(png))
    assert sheet_bgr is not None, f"could not decode {png.name}"

    payload = cnn_reader._read_sheet(model, sheet_bgr)
    err = payload.get("error")

    assert len(payload.get("cards", [])) == exp["cards"], (
        f"{png.name}: expected {exp['cards']} card(s), got "
        f"{len(payload.get('cards', []))} (error={err})")

    dbg = payload.get("debug", {})
    assert dbg.get("partial_sheet", False) == exp["partial_sheet"], (
        f"{png.name}: partial_sheet mismatch (expected "
        f"{exp['partial_sheet']})")

    if exp["error"] is not None:
        assert err is not None, (
            f"{png.name}: expected an error ('{exp['error'][:40]}') but the "
            "read succeeded")
        return

    assert err is None, f"{png.name}: unexpectedly errored: {err[:80]}"

    mismatches = 0
    for ci, exp_grid in enumerate(exp["grids"]):
        got = _grid_values(payload, ci)
        for r in range(5):
            for c in range(5):
                if (r, c) == FREE:
                    continue
                if got[r][c] != exp_grid[r][c]:
                    mismatches += 1
    assert mismatches == 0, (
        f"{png.name}: {mismatches} cells differ from golden grid "
        "(reader/cell-extraction regression?)")


def test_manifest_dumps_present():
    assert len(CASES) >= 10, "regression corpus should stay non-trivial"
    for ts, png, exp in CASES:
        assert png.is_file(), png


if __name__ == "__main__":
    if "--rewrite-manifest" in sys.argv:
        import time
        model = cnn_reader.load_model()
        manifest = {}
        for png in sorted(DUMP_DIR.glob("in_*.png")):
            ts = png.stem.split("_")[1]
            sheet = cv2.imread(str(png))
            payload = cnn_reader._read_sheet(model, sheet)
            err = payload.get("error")
            manifest[ts] = {
                "cards": len(payload.get("cards", [])),
                "partial_sheet": payload.get("debug", {}).get(
                    "partial_sheet", False),
                "error": err,
                "grids": [_grid_values(payload, i)
                          for i in range(len(payload.get("cards", [])))],
            }
            time.sleep(0.05)
        MANIFEST.write_text(json.dumps(manifest, indent=1))
        print(f"rewrote {MANIFEST} ({len(manifest)} entries)")
    else:
        sys.exit(pytest.main([__file__, "-v"]))